/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#a4c9ff",
        "primary-container": "#60a5fa",
        "secondary-fixed": "#e8ddff",
        "on-primary-fixed-variant": "#004883",
        "on-tertiary-fixed-variant": "#5d4200",
        "tertiary-container": "#d19900",
        "surface-tint": "#a4c9ff",
        "inverse-primary": "#0060ac",
        "surface-dim": "#131316",
        "on-secondary-fixed-variant": "#4f319c",
        "tertiary-fixed-dim": "#fabd34",
        "on-background": "#e4e1e6",
        "surface-container-highest": "#353438",
        "error": "#ffb4ab",
        "on-tertiary": "#412d00",
        "outline-variant": "#414751",
        "surface-container": "#1f1f22",
        "on-tertiary-fixed": "#261900",
        "inverse-surface": "#e4e1e6",
        "surface-container-low": "#1b1b1e",
        "surface-container-high": "#2a2a2d",
        "tertiary-fixed": "#ffdea4",
        "on-secondary-fixed": "#21005e",
        "on-primary-fixed": "#001c39",
        "on-surface": "#e4e1e6",
        "surface-bright": "#39393c",
        "on-tertiary-container": "#4b3500",
        "primary-fixed": "#d4e3ff",
        "on-secondary-container": "#bea8ff",
        "on-secondary": "#381385",
        "primary": {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        "on-primary-container": "#003a6b",
        "outline": "#8b919d",
        "secondary": {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        "on-surface-variant": "#c1c7d3",
        "inverse-on-surface": "#303033",
        "secondary-fixed-dim": "#cebdff",
        "on-primary": "#00315d",
        "secondary-container": "#4f319c",
        "on-error-container": "#ffdad6",
        "surface": "#131316",
        "surface-variant": "#353438",
        "background": "var(--background)",
        "foreground": "var(--foreground)",
        "card": {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        "muted": {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        "border": "var(--border)",
        "input": "var(--input)",
        "ring": "var(--ring)",
        "destructive": {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        "tertiary": "#fabd34",
        "error-container": "#93000a",
        "surface-container-lowest": "#0e0e11",
        "on-error": "#690005",
        "verdict": {
          survived: "var(--verdict-survived)",
          weakened: "var(--verdict-weakened)",
          broken: "var(--verdict-broken)",
          unresolved: "var(--verdict-unresolved)",
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-1": "0.25rem",
        "gutter": "1rem",
        "space-2": "0.5rem",
        "pane-min-width": "320px",
        "space-6": "1.5rem",
        "space-5": "1.25rem",
        "space-8": "2rem",
        "space-1.5": "0.375rem",
        "space-4": "1rem",
        "space-3": "0.75rem",
        "terminal-line-height": "1.25rem",
      },
      fontFamily: {
        "code-sm": ["JetBrains Mono", "monospace"],
        "code-lg": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "code-md": ["JetBrains Mono", "monospace"],
        "body-xs": ["Inter", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        "code-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "400" }],
        "code-lg": ["14px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-sm": ["15px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "code-md": ["12px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "500" }],
        "body-xs": ["12px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "400" }],
        "label-mono": ["10px", { lineHeight: "12px", letterSpacing: "0.06em", fontWeight: "600" }],
      },
      animation: {
        "pulse-subtle": "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
  plugins: [],
};
