[pytest]
asyncio_mode = auto
testpaths = tests
pythonpath = .
filterwarnings =
    ignore:cannot collect test class 'TestPlanItem'.*:pytest.PytestCollectionWarning
    ignore:.*Using .httpx. with .starlette.testclient.*
    ignore:.*The anyio.abc.BlockingPortal alias is deprecated.*

